// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow that generates draft email replies and suggests actions based on the content of the received email.
 *
 * - draftEmailReplyAndSuggestActions - A function that takes email content and returns a draft reply and suggested actions.
 * - DraftEmailReplyAndSuggestActionsInput - The input type for the draftEmailReplyAndSuggestActions function.
 * - DraftEmailReplyAndSuggestActionsOutput - The return type for the draftEmailReplyAndSuggestActions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DraftEmailReplyAndSuggestActionsInputSchema = z.object({
  emailContent: z.string().describe('The content of the received email.'),
});
export type DraftEmailReplyAndSuggestActionsInput = z.infer<typeof DraftEmailReplyAndSuggestActionsInputSchema>;

const DraftEmailReplyAndSuggestActionsOutputSchema = z.object({
  draftReply: z.string().describe('The draft email reply generated by the AI.'),
  suggestedActions: z.array(z.string()).describe('Suggested actions to take based on the email content (e.g., create quotation, send clarification email).'),
});
export type DraftEmailReplyAndSuggestActionsOutput = z.infer<typeof DraftEmailReplyAndSuggestActionsOutputSchema>;

export async function draftEmailReplyAndSuggestActions(input: DraftEmailReplyAndSuggestActionsInput): Promise<DraftEmailReplyAndSuggestActionsOutput> {
  return draftEmailReplyAndSuggestActionsFlow(input);
}

const draftEmailReplyAndSuggestActionsPrompt = ai.definePrompt({
  name: 'draftEmailReplyAndSuggestActionsPrompt',
  input: {schema: DraftEmailReplyAndSuggestActionsInputSchema},
  output: {schema: DraftEmailReplyAndSuggestActionsOutputSchema},
  prompt: `You are an AI assistant tasked with drafting email replies and suggesting actions based on the content of received emails.

  Analyze the following email content and generate a draft reply that addresses the sender's concerns or requests. Also, suggest a list of appropriate actions to take, such as creating a quotation, sending a clarification email, or forwarding the email to a relevant department.

  Email Content: {{{emailContent}}}

  Draft Reply:
  Suggested Actions (comma separated):
  `, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_ONLY_HIGH',
      },
    ],
  },
});

const draftEmailReplyAndSuggestActionsFlow = ai.defineFlow(
  {
    name: 'draftEmailReplyAndSuggestActionsFlow',
    inputSchema: DraftEmailReplyAndSuggestActionsInputSchema,
    outputSchema: DraftEmailReplyAndSuggestActionsOutputSchema,
  },
  async input => {
    const {output} = await draftEmailReplyAndSuggestActionsPrompt(input);
    return output!;
  }
);
